In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
torch.manual_seed(1)

# 단순 선형 회귀

In [3]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [4]:
model = nn.Linear(in_features=1, out_features=1)

하나의 입력 x에 대해 하나의 출력 y를 가지므로 입출력 차원 모두 1을 사용하였다. model에는 가중치 W와 편향 b가 저장되어 있는데 이 건 model.parameters()로 불러올 수 있다.

In [5]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [6]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [7]:
nb_epochs = 2000

for epoch in range(nb_epochs + 1):
    pred = model(x_train)

    cost = F.mse_loss(pred, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print(f"Epoch {epoch:4d}/{nb_epochs} Cost: {cost.item():.6f}")

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [8]:
new_var = torch.FloatTensor([[4.0]])
pred_y = model(new_var)
pred_y

tensor([[7.9989]], grad_fn=<AddmmBackward0>)

In [9]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


# 다중 선형 회귀

In [10]:
x_train = torch.FloatTensor(
    [[73, 80, 75], [93, 88, 93], [89, 91, 90], [96, 98, 100], [73, 66, 70]]
)
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [11]:
model = nn.Linear(3, 1)

In [12]:
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1119,  0.2710, -0.5435]], requires_grad=True), Parameter containing:
tensor([0.3462], requires_grad=True)]


In [13]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [14]:
nb_epochs = 2000

for epoch in range(nb_epochs + 1):
    pred = model(x_train)

    cost = F.mse_loss(pred, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print(f"Epoch {epoch:4d}/{nb_epochs} Cost: {cost.item():.6f}")

Epoch    0/2000 Cost: 42134.707031
Epoch  100/2000 Cost: 5.960090
Epoch  200/2000 Cost: 5.654707
Epoch  300/2000 Cost: 5.365413
Epoch  400/2000 Cost: 5.091413
Epoch  500/2000 Cost: 4.831860
Epoch  600/2000 Cost: 4.585968
Epoch  700/2000 Cost: 4.353065
Epoch  800/2000 Cost: 4.132451
Epoch  900/2000 Cost: 3.923481
Epoch 1000/2000 Cost: 3.725512
Epoch 1100/2000 Cost: 3.537961
Epoch 1200/2000 Cost: 3.360339
Epoch 1300/2000 Cost: 3.192072
Epoch 1400/2000 Cost: 3.032686
Epoch 1500/2000 Cost: 2.881712
Epoch 1600/2000 Cost: 2.738675
Epoch 1700/2000 Cost: 2.603187
Epoch 1800/2000 Cost: 2.474835
Epoch 1900/2000 Cost: 2.353291
Epoch 2000/2000 Cost: 2.238128


In [15]:
new_var = torch.FloatTensor([[73, 80, 75]])
pred_y = model(new_var)
pred_y

tensor([[153.7184]], grad_fn=<AddmmBackward0>)

In [16]:
list(model.parameters())

[Parameter containing:
 tensor([[0.8541, 0.8475, 0.3096]], requires_grad=True),
 Parameter containing:
 tensor([0.3568], requires_grad=True)]

# 클래스로 구현하기

In [17]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)

    def forward(self, x):
        return self.linear(x)

In [18]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)

    def forward(self, x):
        return self.linear(x)